import { rtdb } from '@/lib/firebase';
import { 
  ref, 
  push, 
  set,
  get,
  update,
  remove,
  query,
  orderByChild,
  equalTo,
  limitToFirst,
  onValue,
  off,
  serverTimestamp 
} from 'firebase/database';

// ===========================
// TYPE DEFINITIONS
// ===========================

export interface EventData {
  eventId?: string;
  organizerId: string;
  organizerEmail?: string;
  status: 'draft' | 'published' | 'cancelled' | 'completed';
  createdAt?: any;
  updatedAt?: any;
  basicInfo: {
    title: string;
    description: string;
    category: string;
    videoUrl?: string | null;
    bannerImage?: string | null;
  };
  schedule: {
    startDate: string;
    startTime: string;
    endDate: string;
    endTime: string;
    timezone: string;
    recurring: boolean;
    frequency?: string | null;
  };
  venue: {
    name: string;
    address: string;
    city: string;
    capacity: number;
    coordinates?: { lat: number; lng: number };
    zones?: Array<{ name: string; capacity: number }>;
  };
  tickets: Array<{
    id?: string;
    name: string;
    price: number;
    quantity: number;
    sold?: number;
    earlyBird?: boolean;
  }>;
  promoCodes?: Array<{
    code: string;
    discount: string;
    limit: number;
    used?: number;
  }>;
  iotGates?: Array<{
    id: string;
    name: string;
    type: string;
    assigned: boolean;
    accessRule: string;
    sensorConfig: boolean;
  }>;
  settings?: {
    amenities?: {
      wifi?: boolean;
      parking?: boolean;
      wheelchair?: boolean;
    };
    services?: {
      merch?: boolean;
      food?: boolean;
      vipLounge?: boolean;
    };
    ageRestriction?: string;
    refundPolicy?: string;
  };
  analytics?: {
    views?: number;
    bookmarks?: number;
    checkIns?: number;
    revenue?: number;
  };
}

// ===========================
// CREATE EVENT (Legacy function preserved)
// ===========================

/**
 * Creates a new event in Firebase Realtime Database
 * @param eventData - The form data from the event creation page
 * @param userId - The organizer's user ID
 * @returns The unique event ID (key) generated by Firebase
 * @deprecated Use createEvent instead
 */
export const createEventInRealtimeDB = async (eventData: any, userId: string) => {
  try {
    // 1. Create a reference to the 'events' path
    const eventsRef = ref(rtdb, 'events');

    // 2. Generate a unique key for the new event
    const newEventRef = push(eventsRef);

    // 3. Construct the payload with the structure defined in the JSON schema
    const payload = {
      eventId: newEventRef.key,
      organizerId: userId,
      organizerEmail: eventData.organizerEmail || null,
      status: 'published',
      createdAt: serverTimestamp(), // Server-side timestamp
      
      // Basic Information
      basicInfo: {
        title: eventData.title,
        description: eventData.description,
        category: eventData.category,
        videoUrl: eventData.videoUrl || null,
        bannerImage: eventData.image || null
      },
      
      // Schedule Details
      schedule: {
        startDate: eventData.startDate,
        startTime: eventData.startTime,
        endDate: eventData.endDate,
        endTime: eventData.endTime,
        timezone: eventData.timezone,
        recurring: eventData.recurring,
        frequency: eventData.recurring ? eventData.recurringFrequency : null
      },
      
      // Venue Information
      venue: {
        name: eventData.venueName,
        address: eventData.address,
        city: eventData.city,
        capacity: Number(eventData.capacity) || 0,
        coordinates: eventData.coordinates || { lat: 0, lng: 0 },
        zones: eventData.zones.map((z: any) => ({
          name: z.name,
          capacity: Number(z.capacity) || 0
        }))
      },
      
      // Ticket Configuration
      tickets: eventData.tickets.map((t: any) => ({
        name: t.name,
        price: Number(t.price) || 0,
        quantity: Number(t.quantity) || 0,
        earlyBird: t.earlyBird || false
      })),
      
      // Promo Codes
      promoCodes: eventData.promoCodes.map((p: any) => ({
        code: p.code,
        discount: p.discount,
        limit: Number(p.limit) || 0
      })),
      
      // IoT Gates (only store assigned gates)
      iotGates: eventData.gates
        .filter((g: any) => g.assigned)
        .map((g: any) => ({
          id: g.id,
          name: g.name,
          type: g.type,
          assigned: g.assigned,
          accessRule: g.accessRule,
          sensorConfig: g.sensorConfig
        })),
      
      // Advanced Settings
      settings: {
        amenities: eventData.amenities,
        services: eventData.services,
        ageRestriction: eventData.ageRestriction,
        refundPolicy: eventData.refundPolicy || ''
      }
    };

    // 4. Save the data to the specific reference
    await set(newEventRef, payload);
    
    console.log("✅ Event created successfully in Realtime Database!");
    console.log("📍 Event ID:", newEventRef.key);
    return newEventRef.key;

  } catch (error) {
    console.error("❌ Error creating event:", error);
    throw error;
  }
};

/**
 * Helper type for the event data structure
 */
export interface EventPayload {
  eventId: string | null;
  organizerId: string;
  organizerEmail?: string;
  status: string;
  createdAt: any;
  basicInfo: {
    title: string;
    description: string;
    category: string;
    videoUrl: string | null;
    bannerImage: string | null;
  };
  schedule: {
    startDate: string;
    startTime: string;
    endDate: string;
    endTime: string;
    timezone: string;
    recurring: boolean;
    frequency: string | null;
  };
  venue: {
    name: string;
    address: string;
    city: string;
    capacity: number;
    coordinates: { lat: number; lng: number };
    zones: Array<{ name: string; capacity: number }>;
  };
  tickets: Array<{
    name: string;
    price: number;
    quantity: number;
    earlyBird: boolean;
  }>;
  promoCodes: Array<{
    code: string;
    discount: string;
    limit: number;
  }>;
  iotGates: Array<{
    id: string;
    name: string;
    type: string;
    assigned: boolean;
    accessRule: string;
    sensorConfig: boolean;
  }>;
  settings: {
    amenities: {
      wifi: boolean;
      parking: boolean;
      wheelchair: boolean;
    };
    services: {
      merch: boolean;
      food: boolean;
      vipLounge: boolean;
    };
    ageRestriction: string;
    refundPolicy: string;
  };
}

// ===========================
// ENHANCED CREATE EVENT
// ===========================

/**
 * Create a new event in Firebase Realtime Database
 * Modern implementation with better typing
 */
export const createEvent = async (
  eventData: Omit<EventData, 'eventId' | 'createdAt' | 'updatedAt'>,
  userId: string
): Promise<string> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    const newEventRef = push(eventsRef);
    
    const payload: EventData = {
      ...eventData,
      eventId: newEventRef.key || '',
      organizerId: userId,
      status: eventData.status || 'draft',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };

    await set(newEventRef, payload);
    
    // Also add to user's events list
    const userEventRef = ref(rtdb, `users/${userId}/events/${newEventRef.key}`);
    await set(userEventRef, true);
    
    console.log('✅ Event created:', newEventRef.key);
    return newEventRef.key!;
  } catch (error) {
    console.error('❌ Error creating event:', error);
    throw error;
  }
};

// ===========================
// READ EVENTS
// ===========================

/**
 * Get a single event by ID
 */
export const getEventById = async (eventId: string): Promise<EventData | null> => {
  try {
    const eventRef = ref(rtdb, `events/${eventId}`);
    const snapshot = await get(eventRef);
    
    if (snapshot.exists()) {
      return snapshot.val() as EventData;
    }
    return null;
  } catch (error) {
    console.error('❌ Error fetching event:', error);
    throw error;
  }
};

/**
 * Get all events (with optional limit)
 */
export const getAllEvents = async (limit?: number): Promise<EventData[]> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    const eventsQuery = limit 
      ? query(eventsRef, limitToFirst(limit))
      : eventsRef;
    
    const snapshot = await get(eventsQuery);
    
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      return Object.values(eventsObj) as EventData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching events:', error);
    throw error;
  }
};

/**
 * Get events by organizer ID
 */
export const getEventsByOrganizer = async (organizerId: string): Promise<EventData[]> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    const eventsQuery = query(
      eventsRef,
      orderByChild('organizerId'),
      equalTo(organizerId)
    );
    
    const snapshot = await get(eventsQuery);
    
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      return Object.values(eventsObj) as EventData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching organizer events:', error);
    throw error;
  }
};

/**
 * Get events by status
 */
export const getEventsByStatus = async (
  status: 'draft' | 'published' | 'cancelled' | 'completed'
): Promise<EventData[]> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    const eventsQuery = query(
      eventsRef,
      orderByChild('status'),
      equalTo(status)
    );
    
    const snapshot = await get(eventsQuery);
    
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      return Object.values(eventsObj) as EventData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching events by status:', error);
    throw error;
  }
};

/**
 * Get events by category
 */
export const getEventsByCategory = async (category: string): Promise<EventData[]> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    const eventsQuery = query(
      eventsRef,
      orderByChild('basicInfo/category'),
      equalTo(category)
    );
    
    const snapshot = await get(eventsQuery);
    
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      return Object.values(eventsObj) as EventData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching events by category:', error);
    throw error;
  }
};

// ===========================
// UPDATE EVENT
// ===========================

/**
 * Update an existing event
 */
export const updateEvent = async (
  eventId: string,
  updates: Partial<EventData>
): Promise<void> => {
  try {
    const eventRef = ref(rtdb, `events/${eventId}`);
    
    const payload = {
      ...updates,
      updatedAt: serverTimestamp(),
    };
    
    await update(eventRef, payload);
    console.log('✅ Event updated:', eventId);
  } catch (error) {
    console.error('❌ Error updating event:', error);
    throw error;
  }
};

/**
 * Update event status
 */
export const updateEventStatus = async (
  eventId: string,
  status: 'draft' | 'published' | 'cancelled' | 'completed'
): Promise<void> => {
  try {
    const eventRef = ref(rtdb, `events/${eventId}`);
    await update(eventRef, {
      status,
      updatedAt: serverTimestamp(),
    });
    console.log('✅ Event status updated:', eventId, status);
  } catch (error) {
    console.error('❌ Error updating event status:', error);
    throw error;
  }
};

/**
 * Increment event views
 */
export const incrementEventViews = async (eventId: string): Promise<void> => {
  try {
    const eventRef = ref(rtdb, `events/${eventId}/analytics/views`);
    const snapshot = await get(eventRef);
    const currentViews = snapshot.exists() ? snapshot.val() : 0;
    
    await set(eventRef, currentViews + 1);
  } catch (error) {
    console.error('❌ Error incrementing views:', error);
    throw error;
  }
};

// ===========================
// DELETE EVENT
// ===========================

/**
 * Delete an event
 */
export const deleteEvent = async (eventId: string, userId: string): Promise<void> => {
  try {
    // Delete from events collection
    const eventRef = ref(rtdb, `events/${eventId}`);
    await remove(eventRef);
    
    // Delete from user's events list
    const userEventRef = ref(rtdb, `users/${userId}/events/${eventId}`);
    await remove(userEventRef);
    
    console.log('✅ Event deleted:', eventId);
  } catch (error) {
    console.error('❌ Error deleting event:', error);
    throw error;
  }
};

// ===========================
// REAL-TIME LISTENERS
// ===========================

/**
 * Listen to event changes in real-time
 */
export const subscribeToEvent = (
  eventId: string,
  callback: (event: EventData | null) => void
): (() => void) => {
  const eventRef = ref(rtdb, `events/${eventId}`);
  
  const unsubscribe = onValue(eventRef, (snapshot) => {
    if (snapshot.exists()) {
      callback(snapshot.val() as EventData);
    } else {
      callback(null);
    }
  }, (error) => {
    console.error('❌ Error in event listener:', error);
  });
  
  // Return cleanup function
  return () => off(eventRef, 'value', unsubscribe);
};

/**
 * Listen to all events for an organizer
 */
export const subscribeToOrganizerEvents = (
  organizerId: string,
  callback: (events: EventData[]) => void
): (() => void) => {
  const eventsRef = ref(rtdb, 'events');
  const eventsQuery = query(
    eventsRef,
    orderByChild('organizerId'),
    equalTo(organizerId)
  );
  
  const unsubscribe = onValue(eventsQuery, (snapshot) => {
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      callback(Object.values(eventsObj) as EventData[]);
    } else {
      callback([]);
    }
  }, (error) => {
    console.error('❌ Error in events listener:', error);
  });
  
  return () => off(eventsRef, 'value', unsubscribe);
};

// ===========================
// BOOKMARKS
// ===========================

/**
 * Bookmark an event
 */
export const bookmarkEvent = async (userId: string, eventId: string): Promise<void> => {
  try {
    const bookmarkRef = ref(rtdb, `users/${userId}/bookmarkedEvents/${eventId}`);
    await set(bookmarkRef, true);
    
    // Increment bookmark count
    const eventRef = ref(rtdb, `events/${eventId}/analytics/bookmarks`);
    const snapshot = await get(eventRef);
    const currentBookmarks = snapshot.exists() ? snapshot.val() : 0;
    await set(eventRef, currentBookmarks + 1);
    
    console.log('✅ Event bookmarked');
  } catch (error) {
    console.error('❌ Error bookmarking event:', error);
    throw error;
  }
};

/**
 * Remove bookmark
 */
export const unbookmarkEvent = async (userId: string, eventId: string): Promise<void> => {
  try {
    const bookmarkRef = ref(rtdb, `users/${userId}/bookmarkedEvents/${eventId}`);
    await remove(bookmarkRef);
    
    // Decrement bookmark count
    const eventRef = ref(rtdb, `events/${eventId}/analytics/bookmarks`);
    const snapshot = await get(eventRef);
    const currentBookmarks = snapshot.exists() ? snapshot.val() : 0;
    if (currentBookmarks > 0) {
      await set(eventRef, currentBookmarks - 1);
    }
    
    console.log('✅ Bookmark removed');
  } catch (error) {
    console.error('❌ Error removing bookmark:', error);
    throw error;
  }
};

/**
 * Get user's bookmarked events
 */
export const getUserBookmarks = async (userId: string): Promise<EventData[]> => {
  try {
    const bookmarksRef = ref(rtdb, `users/${userId}/bookmarkedEvents`);
    const snapshot = await get(bookmarksRef);
    
    if (snapshot.exists()) {
      const bookmarkedIds = Object.keys(snapshot.val());
      
      // Fetch all bookmarked events
      const eventPromises = bookmarkedIds.map(id => getEventById(id));
      const events = await Promise.all(eventPromises);
      
      return events.filter(e => e !== null) as EventData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching bookmarks:', error);
    throw error;
  }
};

// ===========================
// PUBLIC EVENTS CATALOG
// ===========================

/**
 * Convert Firebase EventData to frontend Event type
 * This adapter ensures compatibility between Firebase schema and UI components
 */
import type { Event } from '@/features/events/event.types';

export const convertEventDataToEvent = (eventData: EventData): Event => {
  // Calculate availability
  const totalSold = eventData.tickets?.reduce((sum, ticket) => sum + (ticket.sold || 0), 0) || 0;
  const totalCapacity = eventData.venue.capacity;
  
  // Calculate ticket price range
  const prices = eventData.tickets?.map(t => t.price) || [0];
  const minPrice = Math.min(...prices);
  
  return {
    id: eventData.eventId || '',
    title: eventData.basicInfo.title,
    description: eventData.basicInfo.description,
    
    // Date & Time
    date: new Date(`${eventData.schedule.startDate}T${eventData.schedule.startTime}`),
    time: eventData.schedule.startTime,
    endDate: new Date(`${eventData.schedule.endDate}T${eventData.schedule.endTime}`),
    endTime: eventData.schedule.endTime,
    
    // Location
    location: {
      venue: eventData.venue.name,
      address: eventData.venue.address,
      city: eventData.venue.city,
      coordinates: eventData.venue.coordinates,
    },
    
    // Pricing
    price: minPrice,
    currency: 'INR',
    
    // Capacity
    capacity: totalCapacity,
    attendees: totalSold,
    available: totalCapacity - totalSold,
    
    // Categorization
    category: eventData.basicInfo.category,
    tags: [],
    
    // Media
    image: eventData.basicInfo.bannerImage || undefined,
    video: eventData.basicInfo.videoUrl || undefined,
    
    // Organizer
    organizer: {
      id: eventData.organizerId,
      name: eventData.organizerEmail || 'Event Organizer',
      email: eventData.organizerEmail,
    },
    
    // Status
    status: eventData.status,
    isFeatured: false,
    isTrending: (eventData.analytics?.views || 0) > 100,
    
    // Ratings (placeholder - can be enhanced later)
    rating: 4.5,
    reviews: 0,
    
    // Additional
    ticketTiers: eventData.tickets?.map(ticket => ({
      id: ticket.id || Math.random().toString(36).substr(2, 9),
      name: ticket.name,
      price: ticket.price,
      quantity: ticket.quantity,
      available: ticket.quantity - (ticket.sold || 0),
      sold: ticket.sold || 0,
    })) || [],
    
    // Timestamps
    createdAt: eventData.createdAt || new Date(),
    updatedAt: eventData.updatedAt || new Date(),
  };
};

/**
 * Get published events for public catalog
 * Filters only published events and converts to Event type
 */
export const getPublishedEvents = async (): Promise<Event[]> => {
  try {
    const eventsRef = ref(rtdb, 'events');
    
    // First try to get all events to debug
    const allEventsSnapshot = await get(eventsRef);
    console.log('📊 All events in DB:', allEventsSnapshot.exists() ? Object.keys(allEventsSnapshot.val()).length : 0);
    
    if (allEventsSnapshot.exists()) {
      const allEventsObj = allEventsSnapshot.val();
      console.log('📊 Event statuses:', Object.values(allEventsObj).map((e: any) => e.status));
    }
    
    const eventsQuery = query(
      eventsRef,
      orderByChild('status'),
      equalTo('published')
    );
    
    const snapshot = await get(eventsQuery);
    console.log('📊 Published events found:', snapshot.exists());
    
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      const eventDataArray = Object.values(eventsObj) as EventData[];
      console.log('📊 Published events count:', eventDataArray.length);
      
      // Convert to Event type - temporarily disable date filter for debugging
      const now = new Date();
      const convertedEvents = eventDataArray.map(convertEventDataToEvent);
      console.log('📊 Converted events:', convertedEvents.length);
      console.log('📊 Event dates:', convertedEvents.map(e => e.date));
      
      // Filter future events but be more lenient
      const futureEvents = convertedEvents.filter(event => {
        const eventDate = new Date(event.date);
        const isPast = eventDate < now;
        console.log(`📊 Event "${event.title}" date: ${eventDate}, isPast: ${isPast}`);
        return !isPast || isNaN(eventDate.getTime()); // Keep if future OR invalid date
      });
      
      console.log('📊 Future events after filter:', futureEvents.length);
      
      // If no future events, return all converted events for now
      if (futureEvents.length === 0 && convertedEvents.length > 0) {
        console.log('📊 Returning all events (no future events found)');
        return convertedEvents.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
      }
      
      return futureEvents.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    }
    
    console.log('📊 No published events found in database');
    return [];
  } catch (error) {
    console.error('❌ Error fetching published events:', error);
    throw error;
  }
};

/**
 * Get published events with real-time updates
 * Returns a function to unsubscribe
 */
export const subscribeToPublishedEvents = (
  callback: (events: Event[]) => void
): (() => void) => {
  const eventsRef = ref(rtdb, 'events');
  const eventsQuery = query(
    eventsRef,
    orderByChild('status'),
    equalTo('published')
  );
  
  const unsubscribe = onValue(eventsQuery, (snapshot) => {
    if (snapshot.exists()) {
      const eventsObj = snapshot.val();
      const eventDataArray = Object.values(eventsObj) as EventData[];
      
      const now = new Date();
      const events = eventDataArray
        .map(convertEventDataToEvent)
        .filter(event => new Date(event.date) >= now)
        .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
      
      callback(events);
    } else {
      callback([]);
    }
  }, (error) => {
    console.error('❌ Error in events subscription:', error);
  });
  
  return () => off(eventsRef, 'value', unsubscribe);
};

/**
 * Get event categories from Firebase events
 * Returns unique categories from all published events
 */
export const getEventCategories = async (): Promise<string[]> => {
  try {
    const events = await getPublishedEvents();
    const categories = new Set(events.map(event => event.category));
    return Array.from(categories).sort();
  } catch (error) {
    console.error('❌ Error fetching categories:', error);
    return [];
  }
};

// ===========================
// BOOKING MANAGEMENT
// ===========================

/**
 * Booking data structure for Firebase RTDB
 */
export interface BookingData {
  bookingId?: string;
  userId: string;
  eventId: string;
  eventTitle: string;
  organizerId: string;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  createdAt?: any;
  updatedAt?: any;
  items: {
    tickets: Record<string, number>; // tierId: quantity
    addons?: Record<string, boolean>; // addonId: selected
  };
  attendees: Array<{
    name: string;
    email: string;
    specialRequests?: string;
  }>;
  financials: {
    subtotal: number;
    fees: number;
    taxes: number;
    discount: number;
    total: number;
  };
  paymentMethod?: string;
  paymentStatus?: 'pending' | 'paid' | 'failed' | 'refunded';
  paymentId?: string;
}

/**
 * Create a new booking in Firebase RTDB
 */
export const createBooking = async (
  bookingData: Omit<BookingData, 'bookingId' | 'createdAt' | 'updatedAt'>
): Promise<string> => {
  try {
    const bookingsRef = ref(rtdb, 'bookings');
    const newBookingRef = push(bookingsRef);
    
    const payload: BookingData = {
      ...bookingData,
      bookingId: newBookingRef.key || '',
      status: bookingData.status || 'pending',
      paymentStatus: 'pending',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };

    await set(newBookingRef, payload);
    
    console.log('✅ Booking created:', newBookingRef.key);
    return newBookingRef.key || '';
  } catch (error) {
    console.error('❌ Error creating booking:', error);
    throw error;
  }
};

/**
 * Get booking by ID
 */
export const getBookingById = async (bookingId: string): Promise<BookingData | null> => {
  try {
    const bookingRef = ref(rtdb, `bookings/${bookingId}`);
    const snapshot = await get(bookingRef);
    
    if (snapshot.exists()) {
      return snapshot.val() as BookingData;
    }
    return null;
  } catch (error) {
    console.error('❌ Error fetching booking:', error);
    throw error;
  }
};

/**
 * Get all bookings for a user
 */
export const getUserBookings = async (userId: string): Promise<BookingData[]> => {
  try {
    const bookingsRef = ref(rtdb, 'bookings');
    const bookingsQuery = query(
      bookingsRef,
      orderByChild('userId'),
      equalTo(userId)
    );
    
    const snapshot = await get(bookingsQuery);
    
    if (snapshot.exists()) {
      const bookingsObj = snapshot.val();
      return Object.values(bookingsObj) as BookingData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching user bookings:', error);
    throw error;
  }
};

/**
 * Get all bookings for an event
 */
export const getEventBookings = async (eventId: string): Promise<BookingData[]> => {
  try {
    const bookingsRef = ref(rtdb, 'bookings');
    const bookingsQuery = query(
      bookingsRef,
      orderByChild('eventId'),
      equalTo(eventId)
    );
    
    const snapshot = await get(bookingsQuery);
    
    if (snapshot.exists()) {
      const bookingsObj = snapshot.val();
      return Object.values(bookingsObj) as BookingData[];
    }
    return [];
  } catch (error) {
    console.error('❌ Error fetching event bookings:', error);
    throw error;
  }
};

/**
 * Update booking status
 */
export const updateBookingStatus = async (
  bookingId: string,
  status: BookingData['status'],
  paymentStatus?: BookingData['paymentStatus'],
  paymentId?: string
): Promise<void> => {
  try {
    const bookingRef = ref(rtdb, `bookings/${bookingId}`);
    
    const updates: Partial<BookingData> = {
      status,
      updatedAt: serverTimestamp(),
    };
    
    if (paymentStatus) updates.paymentStatus = paymentStatus;
    if (paymentId) updates.paymentId = paymentId;
    
    await update(bookingRef, updates);
    
    console.log('✅ Booking status updated:', bookingId);
  } catch (error) {
    console.error('❌ Error updating booking:', error);
    throw error;
  }
};

/**
 * Cancel a booking
 */
export const cancelBooking = async (bookingId: string): Promise<void> => {
  try {
    await updateBookingStatus(bookingId, 'cancelled');
    
    // TODO: Implement refund logic here
    // TODO: Update event ticket availability
    
    console.log('✅ Booking cancelled:', bookingId);
  } catch (error) {
    console.error('❌ Error cancelling booking:', error);
    throw error;
  }
};

/**
 * Update ticket quantities after booking
 * This should be called after successful payment
 */
export const updateTicketQuantities = async (
  eventId: string,
  ticketUpdates: Record<string, number> // tierId: quantityBooked
): Promise<void> => {
  try {
    const eventRef = ref(rtdb, `events/${eventId}`);
    const snapshot = await get(eventRef);
    
    if (!snapshot.exists()) {
      throw new Error('Event not found');
    }
    
    const eventData = snapshot.val() as EventData;
    
    // Update ticket sold counts
    const updatedTickets = eventData.tickets.map(ticket => {
      const ticketId = ticket.id || '';
      const quantityBooked = ticketUpdates[ticketId] || 0;
      
      return {
        ...ticket,
        sold: (ticket.sold || 0) + quantityBooked,
      };
    });
    
    await update(eventRef, {
      tickets: updatedTickets,
      updatedAt: serverTimestamp(),
    });
    
    console.log('✅ Ticket quantities updated for event:', eventId);
  } catch (error) {
    console.error('❌ Error updating ticket quantities:', error);
    throw error;
  }
};

/**
 * Get all bookings for a user
 */
export const getBookingsByUser = async (userId: string): Promise<BookingData[]> => {
  try {
    const bookingsRef = ref(rtdb, 'bookings');
    const userBookingsQuery = query(bookingsRef, orderByChild('userId'), equalTo(userId));
    const snapshot = await get(userBookingsQuery);
    
    if (!snapshot.exists()) {
      return [];
    }
    
    const bookings: BookingData[] = [];
    snapshot.forEach((childSnapshot) => {
      bookings.push({
        id: childSnapshot.key!,
        ...childSnapshot.val(),
      });
    });
    
    return bookings;
  } catch (error) {
    console.error('❌ Error fetching user bookings:', error);
    return [];
  }
};

/**
 * Get user's saved/favorite events
 */
export const getUserSavedEvents = async (userId: string): Promise<EventData[]> => {
  try {
    const savedRef = ref(rtdb, `users/${userId}/savedEvents`);
    const snapshot = await get(savedRef);
    
    if (!snapshot.exists()) {
      return [];
    }
    
    const savedEventIds = Object.keys(snapshot.val());
    const events: EventData[] = [];
    
    for (const eventId of savedEventIds) {
      const event = await getEventById(eventId);
      if (event) {
        events.push(event);
      }
    }
    
    return events;
  } catch (error) {
    console.error('❌ Error fetching saved events:', error);
    return [];
  }
};
